### ISSUE TITLE
Possibly unhandled Error: {"error":"Unexpected error, please try again"}

### ISSUE THREAD

**Issue by ekkis** [blockchain/api-v1-client-node#100]
I've installed the local service, which I run like this:
```
blockchain-wallet-service start --port=3001 &
```
and in following the directions on the README, I have the following small programme:
```
const MyWallet = require('blockchain.info/MyWallet');
var wallet = new MyWallet('testwallet', 'xxx', {apiHost: 'http://localhost:3001'});
wallet.newAddress().then(console.log)
```
which crashes when run like this:

> Possibly unhandled Error: {"error":"Unexpected error, please try again"}
>     at Object.ensureErrorObject (/tst/node_modules/request-promise/node_modules/bluebird/js/main/util.js:261:20)
>     at Promise._rejectCallback (/tst/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:472:22)
>     at Promise._settlePromiseFromHandler (/tst/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:516:17)
>     at Promise._settlePromiseAt (/tst/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
>     at Promise._settlePromises (/tst/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
>     at Async._drainQueue (/tst/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
>     at Async._drainQueues (/tst/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
>     at Immediate.Async.drainQueues [as _onImmediate] (/tst/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
>     at processImmediate (timers.js:632:19)

this is the most basic of use cases.  what do I need to make this work?

**Comment by ekkis** [comment]
ah.  I need to create the wallet first.  duh.
