### ISSUE TITLE
Possibly unhandled Error: No free outputs to spend

### ISSUE THREAD

**Issue by anjalialance** [blockchain/api-v1-client-node#91]
Hello,

I am new to bitcoin transactions. I am using bitcoinjs-lib and blockexplorer for the transaction. The thing that is happening with me is that if I am entering new address that is generated by bip32 and bip39

The address and private key are-

sender address - motCmpWMeMC6BTRUtryxMATUBCvGorAjcs
private key - L1Eoyo3BN41AAxZE1wrJrHYNoxHZhNrtKtgTHVG1axiXJcs6TCkj
receiver address - myQdZsy9wRd4A7deRBm88RZX9rv19NDGyB

then it is giving me error. Also, if i am entering the address which I have previously used in transaction procedures. It is generating same transaction ids again and again.

The address that i am using for this is -

sender address - mkX9cVJDWjPxxfwNvYg58fbR2vHRfuU6XJ
private key - KwV364bGF83ie4wJSwzV4hccbLeyMnFSVwyPvdMEnU8cr6Nyu25U
receiver address - mthGgBTX1kxibjXwXxy5jraBNtTsajpqSx

> Possibly unhandled Error: No free outputs to spend
at Object.ensureErrorObject (C:\Users\ADMIN\Desktop\btc\node_modules\blockchain.info\node_modules\bluebird\js\main\util.js:261:20)
at Promise._rejectCallback (C:\Users\ADMIN\Desktop\btc\node_modules\blockchain.info\node_modules\bluebird\js\main\promise.js:472:22)
at Promise._settlePromiseFromHandler (C:\Users\ADMIN\Desktop\btc\node_modules\blockchain.info\node_modules\bluebird\js\main\promise.js:516:17)
at Promise._settlePromiseAt (C:\Users\ADMIN\Desktop\btc\node_modules\blockchain.info\node_modules\bluebird\js\main\promise.js:584:18)
at Promise._settlePromises (C:\Users\ADMIN\Desktop\btc\node_modules\blockchain.info\node_modules\bluebird\js\main\promise.js:700:14)
at Async._drainQueue (C:\Users\ADMIN\Desktop\btc\node_modules\blockchain.info\node_modules\bluebird\js\main\async.js:123:16)
at Async._drainQueues (C:\Users\ADMIN\Desktop\btc\node_modules\blockchain.info\node_modules\bluebird\js\main\async.js:133:10)
at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\ADMIN\Desktop\btc\node_modules\blockchain.info\node_modules\bluebird\js\main\async.js:15:14)
at processImmediate (timers.js:632:19)
Possibly unhandled Error: No free outputs to spend
at Object.ensureErrorObject (C:\Users\ADMIN\Desktop\btc\node_modules\blockchain.info\node_modules\bluebird\js\main\util.js:261:20)
at Promise._rejectCallback (C:\Users\ADMIN\Desktop\btc\node_modules\blockchain.info\node_modules\bluebird\js\main\promise.js:472:22)
at Promise._settlePromiseFromHandler (C:\Users\ADMIN\Desktop\btc\node_modules\blockchain.info\node_modules\bluebird\js\main\promise.js:516:17)
at Promise._settlePromiseAt (C:\Users\ADMIN\Desktop\btc\node_modules\blockchain.info\node_modules\bluebird\js\main\promise.js:584:18)
at Promise._settlePromises (C:\Users\ADMIN\Desktop\btc\node_modules\blockchain.info\node_modules\bluebird\js\main\promise.js:700:14)
at Async._drainQueue (C:\Users\ADMIN\Desktop\btc\node_modules\blockchain.info\node_modules\bluebird\js\main\async.js:123:16)
at Async._drainQueues (C:\Users\ADMIN\Desktop\btc\node_modules\blockchain.info\node_modules\bluebird\js\main\async.js:133:10)
at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\ADMIN\Desktop\btc\node_modules\blockchain.info\node_modules\bluebird\js\main\async.js:15:14)
at processImmediate (timers.js:632:19)

This is the error.

and Here, is the code for transaction - 

`const bitcoin = require('bitcoinjs-lib')
 const blockexplorer = require('blockchain.info/blockexplorer').usingNetwork(3)
 const wif = 'cRboSi32o7hRLQ2VQMfSDc3SSBayMpxaPvpvPuiX65NXZMwLw1zT'
 const key = bitcoin.ECPair.fromWIF(wif, bitcoin.networks.testnet)
 const wallet = bitcoin.payments.p2pkh({
  pubkey: key.publicKey,
  network: bitcoin.networks.testnet
 })
 blockexplorer.getUnspentOutputs(wallet.address).then(result => {
  wallet.utxos = result.unspent_outputs
  const sending = 10000
  const txb = new bitcoin.TransactionBuilder(bitcoin.networks.testnet)
  txb.setVersion(2)
  var input = 0
  for (let utx of wallet.utxos) {
    txb.addInput(utx.tx_hash_big_endian, utx.tx_output_n)
    input += utx.value
    if (input >= sending) break
  }
  const change1 = 17466476 - sending
  const fee = 1000
  const change = input - (sending + fee)
  txb.addOutput('myQdZsy9wRd4A7deRBm88RZX9rv19NDGyB', sending)
  if (change) txb.addOutput('motCmpWMeMC6BTRUtryxMATUBCvGorAjcs', change)
  txb.sign(0, key)
  const raw = txb.build().toHex()
  console.log(raw)
 })`

This is the code of transaction

and the code for wallet creation is-

`var keyPair = bitcoin.ECPair.makeRandom();
 var testnet = bitcoin.networks.testnet;
 var {address} = bitcoin.payments.p2pkh({pubkey : keyPair.publicKey, network: testnet});
 var privateKey=keyPair.toWIF();`

Thanks in advance!

**Comment by ShabanGomaa** [comment]
I have the same issue
When I use
blockexplorer.getUnspentOutputs(address) 
I get error:  No free outputs to spend

**Comment by anjalialance** [comment]
Yes, I am just trying to find out what's the loop hole but got no clue. I have checked all my code at least 3 times. But got nothing.

**Comment by jtormey** [comment]
This should be resolved, are you still seeing issues?

**Comment by anjalialance** [comment]
No, I am not seeing the issue now. I am closing this then. 👍
